name: Publish to NPM

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run:  publnpmish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
